version: "3.9"
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwd"
    ports:
      - "5432:5432"
    networks:
      - flight_booking_backend
    volumes:
      - "postgres_data:/data/db"

  flight_booking:
    container_name: flight_booking
    build: .
    env_file:
      - "local.env"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - flight_booking_backend
    volumes:
      - "flight_booking_data:/app"

  migrate:
    image: migrate/migrate
    container_name: migrate
    restart: on-failure
    command:
      [
        "-source",
        "file://migrations",
        "-database",
        "postgres://postgres:passwd@postgres_db:5432/postgres?sslmode=disable",
        "up"
      ]
    links:
      - postgres_db
    depends_on:
      - postgres_db
    networks:
      - flight_booking_backend
    volumes:
      - ./migrations/:/migrations

volumes:
  flight_booking_data:
  postgres_data:


networks:
  flight_booking_backend:
    driver: bridge
